In [1]:
import tensorflow as tf

D:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
import numpy as np

## 0 准备数据集

In [3]:
#一次喂给神经网络的数据量
BATCH_SIZE = 8
#随机种子
seed = 23455

In [4]:
rng = np.random.RandomState(seed)

In [5]:
#返回32行2列的随机矩阵，表示32组原件的体积和重量，作为输入数据集
X = rng.rand(32,2)
#从X这个32行2列的矩阵中，取出一行，判断如果和小于1给Y赋值1
Y = [[int(x0 + x1 < 1)] for (x0, x1) in X]

In [6]:
print("X:\r\n",X)

X:
 [[0.83494319 0.11482951]
 [0.66899751 0.46594987]
 [0.60181666 0.58838408]
 [0.31836656 0.20502072]
 [0.87043944 0.02679395]
 [0.41539811 0.43938369]
 [0.68635684 0.24833404]
 [0.97315228 0.68541849]
 [0.03081617 0.89479913]
 [0.24665715 0.28584862]
 [0.31375667 0.47718349]
 [0.56689254 0.77079148]
 [0.7321604  0.35828963]
 [0.15724842 0.94294584]
 [0.34933722 0.84634483]
 [0.50304053 0.81299619]
 [0.23869886 0.9895604 ]
 [0.4636501  0.32531094]
 [0.36510487 0.97365522]
 [0.73350238 0.83833013]
 [0.61810158 0.12580353]
 [0.59274817 0.18779828]
 [0.87150299 0.34679501]
 [0.25883219 0.50002932]
 [0.75690948 0.83429824]
 [0.29316649 0.05646578]
 [0.10409134 0.88235166]
 [0.06727785 0.57784761]
 [0.38492705 0.48384792]
 [0.69234428 0.19687348]
 [0.42783492 0.73416985]
 [0.09696069 0.04883936]]


In [7]:
print("X:\r\n",Y)

X:
 [[1], [0], [0], [1], [1], [1], [1], [0], [1], [1], [1], [0], [0], [0], [0], [0], [0], [1], [0], [0], [1], [1], [0], [1], [0], [1], [1], [1], [1], [1], [0], [1]]


## 1 定义神经网络的输入、参数和输出，定义前向传播过程

In [8]:
x = tf.placeholder(dtype=tf.float32, shape=(None, 2))
#y_是真值
y_ = tf.placeholder(dtype=tf.float32, shape=(None, 1))

In [9]:
w1 = tf.Variable(tf.random_normal([2,3], stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal([3,1], stddev=1, seed=1))

In [10]:
a = tf.matmul(x, w1)
#y是计算出来的值
y = tf.matmul(a, w2)

## 2 定义损失函数和反向传播

In [11]:
loss = tf.reduce_mean(tf.square(y-y_))
train_step = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

## 3 生成会话，训练steps轮

In [12]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    print("w1:\r\n",sess.run(w1))
    print("w2:\r\n",sess.run(w2))
    STEPS = 3000
    for i in range(STEPS):
        #一次喂8个 8个8个地轮流喂
        start = (i*BATCH_SIZE) % 32
        end = start + BATCH_SIZE
        sess.run(train_step, feed_dict={x:X[start:end], y_:Y[start:end]})
        if i % 300 == 0:
            total_loss = sess.run(loss, feed_dict={x:X, y_:Y})
            print("After %d training steps, loss on all data is %g" %(i, total_loss))

    print("\r\n")
    print("w1:\r\n",sess.run(w1))
    print("w2:\r\n",sess.run(w2))

w1:
 [[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
w2:
 [[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
After 0 training steps, loss on all data is 5.13118
After 300 training steps, loss on all data is 0.468183
After 600 training steps, loss on all data is 0.42348
After 900 training steps, loss on all data is 0.412545
After 1200 training steps, loss on all data is 0.405167
After 1500 training steps, loss on all data is 0.399923
After 1800 training steps, loss on all data is 0.396114
After 2100 training steps, loss on all data is 0.393297
After 2400 training steps, loss on all data is 0.391181
After 2700 training steps, loss on all data is 0.389573


w1:
 [[-0.7000663   0.91363174  0.0895357 ]
 [-2.3402493  -0.14641264  0.58823055]]
w2:
 [[-0.06024268]
 [ 0.91956186]
 [-0.06820709]]
