In [1]:
import tensorflow as tf
import numpy as np

D:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
BATCH_SIZE = 8
SEED = 23455

## 0 准备数据集合

In [3]:
rdm = np.random.RandomState(SEED)
X = rdm.rand(32,2)
Y_ = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1,x2) in X]

## 1 定义神经网络的输入、参数和输出，定义向前传播过程

In [4]:
x = tf.placeholder(tf.float32, shape=(None, 2))
y_ = tf.placeholder(tf.float32, shape=(None, 1))
w1 = tf.Variable(tf.random_normal([2,1], stddev=1, seed=1))
y = tf.matmul(x, w1)

## 2 定义损失函数以及反向传播方法

In [5]:
#a 标准的mse损失函数
#loss = tf.reduce_mean(tf.square(y-y_))
#b 加权损失函数 分段函数 预测值大于真实值(酸奶做多了，损失成本) 反之损失收益
COST = 1
PROFIT = 9
loss = tf.reduce_mean(tf.where(tf.greater(y, y_), (y-y_)*COST, (y_-y)*PROFIT ))
opt = tf.train.GradientDescentOptimizer(0.001)

In [6]:
train_step = opt.minimize(loss)

In [7]:
with tf.Session() as sess:
    #初始化所有变量
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 20000
    for i in range(STEPS):
        start = (i*BATCH_SIZE) % 32
        end = start + BATCH_SIZE
        sess.run(train_step, feed_dict={x:X[start:end], y_:Y_[start:end]})
        if i % 1000 == 0:
            print("After %d training steps, w1 is:" % (i))
            print(sess.run(w1), "\r\n")
    print("Final w1 is: \r\n", sess.run(w1))

After 0 training steps, w1 is:
[[-0.8052776]
 [ 1.4877197]] 

After 1000 training steps, w1 is:
[[0.7987175]
 [1.9026194]] 

After 2000 training steps, w1 is:
[[0.94721854]
 [1.473387  ]] 

After 3000 training steps, w1 is:
[[1.002287 ]
 [1.0734401]] 

After 4000 training steps, w1 is:
[[1.0180526]
 [1.0440917]] 

After 5000 training steps, w1 is:
[[1.0176336]
 [1.0453868]] 

After 6000 training steps, w1 is:
[[1.01775  ]
 [1.0449886]] 

After 7000 training steps, w1 is:
[[1.0176187]
 [1.0449595]] 

After 8000 training steps, w1 is:
[[1.018133 ]
 [1.0448177]] 

After 9000 training steps, w1 is:
[[1.0175838]
 [1.0450099]] 

After 10000 training steps, w1 is:
[[1.0177003]
 [1.0446117]] 

After 11000 training steps, w1 is:
[[1.017569 ]
 [1.0445826]] 

After 12000 training steps, w1 is:
[[1.0176655]
 [1.044662 ]] 

After 13000 training steps, w1 is:
[[1.0185778]
 [1.0447764]] 

After 14000 training steps, w1 is:
[[1.0177808]
 [1.0453377]] 

After 15000 training steps, w1 is:
[[1.018543 ]
 